# AULA 23/10 — SIMULADO GUIADO DO MINI-PROJETO M1.1
## Sprint 5, Sprint 6 e revisão completa

Hoje você fará um **mini-projeto de treino completo**, usando uma base diferente da avaliação.

### Regra da aula
Tente resolver cada etapa sozinho antes de consultar anotações.

### Produto final do simulado
- notebook organizado;
- `varejo_simulado_limpo.csv`;
- 3 a 6 conclusões;
- recomendação;
- limitação;
- rascunho de README.

In [1]:
from google.colab import files
uploaded = files.upload()

import pandas as pd

nome_arquivo = next(iter(uploaded))

df_original = pd.read_csv(nome_arquivo)

Saving varejo_simulado_avaliacao.csv to varejo_simulado_avaliacao.csv

# SPRINT 1 — LEITURA E DIAGNÓSTICO

In [2]:
# Leitura da base primeiras 5 linhas
display(df_original.head())

,registro_id,cliente_id,genero,categoria,valor_compra,quantidade,cidade,canal
0,R0001,C009,Masculino,Alimentos,348.79,4,Salvador,App
1,R0002,C017,Masculino,Alimentos,642.97,6,Belo Horizonte,Loja
2,R0003,C002,Masculino,Moda,220.80,4,Belo Horizonte,App
3,R0004,C017,Feminino,moda,891.57,1,Curitiba,Loja
4,R0005,C010,Masculino,Beleza,912.45,5,Belo Horizonte,Loja

In [3]:
# Tamanho da base e conhecer as colunas

print("Dimensões: ", df_original.shape)
print("Colunas: ", df_original.columns.tolist())

Dimensões:  (50, 8)
Colunas:  ['registro_id', 'cliente_id', 'genero', 'categoria', 'valor_compra', 'quantidade', 'cidade', 'canal']

In [4]:
# Info da base
df_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   registro_id   50 non-null     object
 1   cliente_id    50 non-null     object
 2   genero        50 non-null     object
 3   categoria     50 non-null     object
 4   valor_compra  48 non-null     float64
 5   quantidade    50 non-null     int64
 6   cidade        50 non-null     object
 7   canal         50 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 3.3+ KB

In [11]:
# Valores nulos

display(df_original.isna().sum())

# Duplicatas
print(
    "Duplicatas completas excedentes:",
    df_original.duplicated().sum()
)

registro_id     0
cliente_id      0
genero          0
categoria       0
valor_compra    2
quantidade      0
cidade          0
canal           0
dtype: int64

Duplicatas completas excedentes: 2

In [13]:
#Visualizando onde estão as duplicatas
display(df_original.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48     True
49     True
dtype: bool

In [7]:
# Inconscistências textuais

# Para espaços

colunas_texto = [
    "registro_id",
    "cliente_id",
    "genero",
    "categoria",
    "cidade",
    "canal"
]

for coluna in colunas_texto:
    quantidade_em_branco = (
        df_original[coluna]
        .astype("string")
        .str.strip()
        .eq("")
        .sum()
    )

    print(coluna, ":", quantidade_em_branco)

registro_id : 0
cliente_id : 0
genero : 1
categoria : 0
cidade : 0
canal : 0

In [8]:
# Diferenças de escrita

for coluna in ["genero", "categoria", "cidade", "canal", "registro_id", "cliente_id"]:
  print(coluna)
  print(df_original[coluna].unique())

genero
['Masculino' 'Feminino' 'Não informado' ' ']
categoria
['Alimentos' 'Moda' 'moda ' 'Beleza' 'Eletrônicos' 'Casa' 'ELETRÔNICOS']
cidade
['Salvador' 'Belo Horizonte' 'Curitiba' 'rio de janeiro' 'São Paulo'
 'Rio de Janeiro' 'SÃO PAULO ']
canal
['App' 'Loja' 'Site']
registro_id
['R0001' 'R0002' 'R0003' 'R0004' 'R0005' 'R0006' 'R0007' 'R0008' 'R0009'
 'R0010' 'R0011' 'R0012' 'R0013' 'R0014' 'R0015' 'R0016' 'R0017' 'R0018'
 'R0019' 'R0020' 'R0021' 'R0022' 'R0023' 'R0024' 'R0025' 'R0026' 'R0027'
 'R0028' 'R0029' 'R0030' 'R0031' 'R0032' 'R0033' 'R0034' 'R0035' 'R0036'
 'R0037' 'R0038' 'R0039' 'R0040' 'R0041' 'R0042' 'R0043' 'R0044' 'R0045'
 'R0046' 'R0047' 'R0048']
cliente_id
['C009' 'C017' 'C002' 'C010' 'C018' 'C003' 'C008' 'C006' 'C016' 'C023'
 'C021' 'C007' 'C012' 'C019' 'C013' 'C011' 'C005' 'C004' 'C001' 'C014'
 'C022']

In [14]:
df_original.head(50)

,registro_id,cliente_id,genero,categoria,valor_compra,quantidade,cidade,canal
0,R0001,C009,Masculino,Alimentos,348.79,4,Salvador,App
1,R0002,C017,Masculino,Alimentos,642.97,6,Belo Horizonte,Loja
2,R0003,C002,Masculino,Moda,220.80,4,Belo Horizonte,App
3,R0004,C017,Feminino,moda,891.57,1,Curitiba,Loja
4,R0005,C010,Masculino,Beleza,912.45,5,Belo Horizonte,Loja
5,R0006,C018,Não informado,Alimentos,949.51,2,Curitiba,Site
6,R0007,C003,Não informado,Eletrônicos,438.90,9,Salvador,Loja
7,R0008,C008,Masculino,Alimentos,776.59,9,rio de janeiro,Site
8,R0009,C006,Masculino,Moda,1450.93,3,Belo Horizonte,Site
9,R0010,C016,Masculino,Eletrônicos,NaN,9,Belo Horizonte,App
10,R0011,C023,Não informado,Eletrônicos,1003.29,5,São Paulo,Site
11,R0012,C003,Feminino,Beleza,1000.46,1,Rio de Janeiro,App
12,R0013,C021,Masculino,Moda,235.07,8,Curitiba,Site
13,R0014,C007,Masculino,Beleza,355.17,1,Salvador,App
14,R0015,C012,Feminino,Beleza,156.74,8,Rio de Janeiro,Site
15,R0016,C019,Não informado,Casa,962.38,4,Curitiba,Loja
16,R0017,C013,,Eletrônicos,589.95,6,Curitiba,Loja
17,R0018,C011,Feminino,Eletrônicos,1324.16,7,Rio de Janeiro,Site
18,R0019,C019,Masculino,ELETRÔNICOS,436.99,1,São Paulo,Site
19,R0020,C005,Masculino,Casa,466.04,3,Rio de Janeiro,App
20,R0021,C004,Não informado,Moda,614.93,9,Curitiba,Loja
21,R0022,C017,Não informado,Beleza,721.22,5,SÃO PAULO,Loja
22,R0023,C023,Não informado,Casa,1334.38,8,Salvador,Loja
23,R0024,C008,Feminino,Eletrônicos,467.25,9,Salvador,Site
24,R0025,C002,Masculino,Moda,88.90,4,Rio de Janeiro,Site
25,R0026,C001,Masculino,Eletrônicos,865.33,3,Rio de Janeiro,App
26,R0027,C014,Masculino,Alimentos,568.85,5,Salvador,App
27,R0028,C002,Feminino,Casa,269.10,8,Belo Horizonte,Site
28,R0029,C006,Masculino,Beleza,1099.38,4,Rio de Janeiro,Loja
29,R0030,C007,Feminino,Moda,1351.13,1,Salvador,Site
30,R0031,C004,Masculino,Moda,1454.96,3,Rio de Janeiro,App
31,R0032,C001,Não informado,Beleza,NaN,4,Belo Horizonte,App
32,R0033,C017,Feminino,Moda,98.83,4,São Paulo,App
33,R0034,C008,Feminino,Beleza,654.32,5,Curitiba,Site
34,R0035,C022,Feminino,Casa,303.68,4,Rio de Janeiro,Loja
35,R0036,C018,Feminino,Casa,1479.64,5,Curitiba,App
36,R0037,C007,Não informado,Eletrônicos,174.03,3,São Paulo,App
37,R0038,C017,Masculino,Casa,238.95,6,São Paulo,Loja
38,R0039,C009,Masculino,Eletrônicos,1188.96,5,Salvador,Loja
39,R0040,C018,Masculino,Moda,481.81,3,São Paulo,App
40,R0041,C002,Não informado,Alimentos,626.59,6,Belo Horizonte,App
41,R0042,C014,Feminino,Eletrônicos,221.06,1,São Paulo,Site
42,R0043,C008,Masculino,Beleza,1267.36,4,Salvador,Site
43,R0044,C012,Feminino,Beleza,1031.51,6,São Paulo,Loja
44,R0045,C017,Não informado,Alimentos,1175.30,9,Curitiba,App
45,R0046,C003,Não informado,Alimentos,1007.68,2,Belo Horizonte,Site
46,R0047,C003,Feminino,Alimentos,277.32,6,São Paulo,App
47,R0048,C017,Feminino,Moda,731.62,4,São Paulo,App
48,R0003,C002,Masculino,Moda,220.80,4,Belo Horizonte,App
49,R0012,C003,Feminino,Beleza,1000.46,1,Rio de Janeiro,App

In [15]:
# Visualizando registros de clientes

print(
    "Registros distintos: ",
    df_original["registro_id"].nunique()
)

print(
    "Identificadores de clientes distintos: ",
    df_original["cliente_id"].nunique()
)

Registros distintos:  48
Identificadores de clientes distintos:  21

In [16]:
display(
    df_original.loc[
      df_original["cliente_id"] == "C017",
        ["registro_id", "cliente_id", "genero"]
    ]
)

   registro_id cliente_id         genero
1        R0002       C017      Masculino
3        R0004       C017       Feminino
21       R0022       C017  Não informado
32       R0033       C017       Feminino
37       R0038       C017      Masculino
44       R0045       C017  Não informado
47       R0048       C017       Feminino

Encontramos sete registros do cliente C017, mas o gênero varia entre eles. Isso mostra que devemos preservar os dados e registrar essa diferença, porque ainda não temos evidências para escolher o preenchimento. Portanto, não vamos usar gênero como agrupamento e análise nesse caso.

### Conclusão de leitura e diagnóstico

| Verificação | Resultado |
|---|---|
| Dimensões | 50 linhas e 8 colunas |
| `registro_id` distintos | 48 |
| `cliente_id` distintos | 21 |
| Duplicatas completas excedentes | 2 |
| Registros repetidos integralmente | `R0003` e `R0012` |
| Ausências em `valor_compra` | 2: `R0010` e `R0032` |
| Gênero preenchido apenas com espaço | 1: `R0017` |
| Exemplos de variações textuais | `moda `, `ELETRÔNICOS`, `rio de janeiro`, `SÃO PAULO ` |

# SPRINT 2 — LIMPEZA E PADRONIZAÇÃO

| Problema | Decisão | Justificativa |
|---|---|---|
| Espaços e capitalização diferentes | Padronizar os textos | Reunir rótulos equivalentes |
| Gênero contendo apenas espaço | Usar `Não informado` | Tornar explícita a falta da informação |
| Dois valores de compra ausentes | Manter como ausentes | Não há evidência para recuperar os valores |
| Duas cópias completas | Remover as ocorrências excedentes | Evitar contagem e soma duplicadas |
| Gênero variando para o mesmo cliente | Preservar e documentar | A definição exige consulta à origem |

# SPRINT 3 — DUAS FUNÇÕES

Crie:
1. uma função de tratamento;
2. uma função de resumo.

Ambas precisam ter parâmetro e `return`.

In [20]:
# Primeira função de tratamento de dados

def tratar_dados(tabela):
  tratado = tabela.copy()

  for coluna in ["genero", "categoria", "cidade", "canal"]:
    tratado[coluna] = (
        tratado[coluna]
        .astype("string")
        .str.strip()
        .replace("", pd.NA)
        .str.title()
    )

  # Corrigido para usar dicionários no replace
  tratado["genero"] = (
      tratado["genero"]
      .replace("Não Informado", "Não informado")
      .fillna("Não informado")
  )

  tratado["cidade"] = tratado["cidade"].replace({
      "rio de Janeiro": "Rio de Janeiro",
      "SÃO PAULO": "São Paulo"
  })

  tratado["categoria"] = tratado["categoria"].replace({
      "ELETRÔNICOS": "Eletrônicos",
      "moda": "Moda"
  })

  # Retirar a duplicata
  tratado = tratado.drop_duplicates().copy()

  return tratado

In [21]:
# função de valores

def gerar_resumo(tabela):
  valores = tabela["valor_compra"]

  return {
      "contagem_valida": valores.count(),
      "media": valores.mean(),
      "minimo": valores.min(),
      "maximo": valores.max()
  }

In [22]:
df_limpo = tratar_dados(df_original)

resumo = gerar_resumo(df_limpo)

In [23]:
# Conferindo tratamento antes da análise

print("Linhas antes: ", len(df_original))
print("Linhas depois: ", len(df_limpo))

print(
    "Duplicatas restantes: ",
    df_limpo.duplicated().sum()
)

display(df_limpo.isna().sum())

print(
    "Identificadores de clientes distintos: ",
    df_limpo["cliente_id"].nunique()
)

Linhas antes:  50
Linhas depois:  48
Duplicatas restantes:  0

registro_id     0
cliente_id      0
genero          0
categoria       0
valor_compra    2
quantidade      0
cidade          0
canal           0
dtype: int64

Identificadores de clientes distintos:  21

# SPRINT 4 — ANÁLISE

Faça:
- contagem válida, média, mínimo e máximo de uma coluna numérica adequada;
- um filtro;
- dois `groupby()` diferentes;
- interpretação dos resultados.

In [24]:
# Representação das estatísticas

print("Valores válidos: ", resumo["contagem_valida"])
print("Média: ", round(resumo["media"], 2))
print("Mínimo: ", resumo["minimo"])
print("Máximo: ", resumo["maximo"])

Valores válidos:  46
Média:  716.45
Mínimo:  88.9
Máximo:  1479.64

Dos 48 registros tratados, 46 possuem valor de compra preenchido.

A média dos valores de compra conhecidos é de aproximadamente R$ 716,45

In [25]:
# Compras acima do valor da média

registros_acima_media = df_limpo.loc[
    df_limpo["valor_compra"] > resumo["media"],
    ["registro_id", "cliente_id", "valor_compra"]
]

print("Quantidade de registros acima da média: ", len(registros_acima_media))

display(registros_acima_media)

Quantidade de registros acima da média:  22

   registro_id cliente_id  valor_compra
3        R0004       C017        891.57
4        R0005       C010        912.45
5        R0006       C018        949.51
7        R0008       C008        776.59
8        R0009       C006       1450.93
10       R0011       C023       1003.29
11       R0012       C003       1000.46
15       R0016       C019        962.38
17       R0018       C011       1324.16
21       R0022       C017        721.22
22       R0023       C023       1334.38
25       R0026       C001        865.33
28       R0029       C006       1099.38
29       R0030       C007       1351.13
30       R0031       C004       1454.96
35       R0036       C018       1479.64
38       R0039       C009       1188.96
42       R0043       C008       1267.36
43       R0044       C012       1031.51
44       R0045       C017       1175.30
45       R0046       C003       1007.68
47       R0048       C017        731.62

In [27]:
# Filtro de valores acima de 600

registros_acima_600 = df_limpo[
    df_limpo["valor_compra"] > 600

]

print(
    "Registros acima de R$ 600: ",
    len(registros_acima_600)
)

display(registros_acima_600)

Registros acima de R$ 600:  26

,registro_id,cliente_id,genero,categoria,valor_compra,quantidade,cidade,canal
1,R0002,C017,Masculino,Alimentos,642.97,6,Belo Horizonte,Loja
3,R0004,C017,Feminino,Moda,891.57,1,Curitiba,Loja
4,R0005,C010,Masculino,Beleza,912.45,5,Belo Horizonte,Loja
5,R0006,C018,Não informado,Alimentos,949.51,2,Curitiba,Site
7,R0008,C008,Masculino,Alimentos,776.59,9,Rio De Janeiro,Site
8,R0009,C006,Masculino,Moda,1450.93,3,Belo Horizonte,Site
10,R0011,C023,Não informado,Eletrônicos,1003.29,5,São Paulo,Site
11,R0012,C003,Feminino,Beleza,1000.46,1,Rio De Janeiro,App
15,R0016,C019,Não informado,Casa,962.38,4,Curitiba,Loja
17,R0018,C011,Feminino,Eletrônicos,1324.16,7,Rio De Janeiro,Site
20,R0021,C004,Não informado,Moda,614.93,9,Curitiba,Loja
21,R0022,C017,Não informado,Beleza,721.22,5,São Paulo,Loja
22,R0023,C023,Não informado,Casa,1334.38,8,Salvador,Loja
25,R0026,C001,Masculino,Eletrônicos,865.33,3,Rio De Janeiro,App
28,R0029,C006,Masculino,Beleza,1099.38,4,Rio De Janeiro,Loja
29,R0030,C007,Feminino,Moda,1351.13,1,Salvador,Site
30,R0031,C004,Masculino,Moda,1454.96,3,Rio De Janeiro,App
33,R0034,C008,Feminino,Beleza,654.32,5,Curitiba,Site
35,R0036,C018,Feminino,Casa,1479.64,5,Curitiba,App
38,R0039,C009,Masculino,Eletrônicos,1188.96,5,Salvador,Loja
40,R0041,C002,Não informado,Alimentos,626.59,6,Belo Horizonte,App
42,R0043,C008,Masculino,Beleza,1267.36,4,Salvador,Site
43,R0044,C012,Feminino,Beleza,1031.51,6,São Paulo,Loja
44,R0045,C017,Não informado,Alimentos,1175.30,9,Curitiba,App
45,R0046,C003,Não informado,Alimentos,1007.68,2,Belo Horizonte,Site
47,R0048,C017,Feminino,Moda,731.62,4,São Paulo,App

Analisamos 22 registros acima da média de R$ 716,46.

Além disso, vimos a presença de 26 acima do valor de R$ 600.

In [28]:
# Agrupamento por categoria

registros_por_categoria = (
    df_limpo.groupby("categoria")
    .size()
    .sort_values(ascending=False)
)

display(registros_por_categoria)

categoria
Moda           11
Eletrônicos    11
Beleza         10
Alimentos       9
Casa            7
dtype: int64

In [29]:
# Agrupamento por canal

por_canal = (
    df_limpo.groupby("canal")
    .size()
    .sort_values(ascending=False)
)

display(por_canal)

canal
App     18
Site    16
Loja    14
dtype: int64

In [30]:
# Agrupar mais de uma coluna - canal e valor_compra

grupos_canal = (
    df_limpo.groupby("canal")["valor_compra"]

)

resumo_por_canal = pd.DataFrame({
    "registros": grupos_canal.size(),
    "valores_validos": grupos_canal.count(),
    "soma_valores_conhecidos": grupos_canal.sum(min_count=1)
})
display(resumo_por_canal.round(2))

       registros  valores_validos  soma_valores_conhecidos
canal
App           18               16                 10325.54
Loja          14               14                 10971.23
Site          16               16                 11660.08

In [31]:
# Agrupamento de mais de uma coluna - categoria por valor_compra

grupos_categoria = (
    df_limpo.groupby("categoria")["valor_compra"]
    .sum()
    .sort_values(ascending=False)
)

display(grupos_categoria)

categoria
Moda           7620.55
Beleza         7198.61
Eletrônicos    6709.92
Alimentos      6373.60
Casa           5054.17
Name: valor_compra, dtype: float64

Moda e Eletrônicos, possuem a maior quantidade de registros por categoria. O App, possui o maior número de registros em canal.

App apesar de ter o maior número de registros, não possui a maior soma de valor de compra, essa sendo para Site, que possui a soma de valor de compra de R$ 11.660.

Já a categoria Moda, é a que possui o maior valor de compra, com aproximadamente R$ 7.620.

# SPRINT 5 — EXPORTAÇÃO E CONCLUSÕES

Salve:
`varejo_simulado_limpo.csv`

Depois escreva:
- 3 a 6 conclusões numéricas;
- 1 recomendação;
- 1 limitação.

In [32]:
df_limpo.to_csv(
    "varejo_simulado_limpo.csv",
    index=False
)

In [33]:
conferencia = pd.read_csv(
    "varejo_simulado_limpo.csv"
)

print(conferencia.shape)
print(conferencia.columns.tolist())

(48, 8)
['registro_id', 'cliente_id', 'genero', 'categoria', 'valor_compra', 'quantidade', 'cidade', 'canal']

## Modelo de estrutura para conclusão

- **Resultado 1:** ...
- **Resultado 2:** ...
- **Resultado 3:** ...
- **Recomendação:** ...
- **Limitação:** ...

1. Após remover duas cópias completas, a base passou de 50 para 48 registros, mantendo 21 identificadores de clientes distintos;

2. Existem 46 valores de compra preenchidos, cuja média é de R$ 716,45.

3. Os valores conhecidos variam de R$ 88,90
a R$ 1479,64.

4. Foram encontrados 26 registros com valor de compra superior a R$ 600.

E 22 registros com valores acima da média de R$ 716,45.

5. Em categoria, Moda possui o maior número de registros, enquanto que em canal, App é o que possui o maior número de registros. Porém o canal que possui a maior soma de valores conhecidos é Site, com R$ 11.660,08.

Já em categoria, Moda é a que possui a maior soma de valor de compra de R$ 7620,55.

**Recomendação**: Conferir na origem os dois valores de compra ausentes do canal App antes de usar as somas para orientar uma comparação de desempenho.

**Limitação**: A análise de valores utiliza apenas informações preenchidas. Além disso, há rótulos de gênero diferentes em registros associados ao mesmo cliente, o que exiege esclarecimento antes de uma análise de perfil por cliente.

# SPRINT 6 — README E GITHUB

Estrutura mínima sugerida do README:

```markdown
# Mini-Projeto — Seu Nome — T8

## Objetivo

## Origem da base

## Significado das colunas utilizadas

## Etapas do projeto
1. Leitura
2. Diagnóstico
3. Limpeza
4. Funções
5. Análise
6. Exportação

## Decisões de limpeza

## Principais conclusões

## Como executar

## Arquivos
```

### Sugestões de commits
- `inicia estrutura do projeto`
- `adiciona diagnóstico da base`
- `implementa limpeza e funções`
- `adiciona análise e agrupamentos`
- `finaliza README e exportação`

In [35]:
# PARAGRAFO DE PROCESSO README

print(
    "Soma antes: ",
    round(df_original["valor_compra"].sum(), 2)
)

print(
    "Soma depois: ",
    round(df_limpo["valor_compra"].sum(), 2)
)

Soma antes:  34178.11
Soma depois:  32956.85

# Exemplo de paragrafo no ReadMe:

A leitura do CSV foi realizada com pd.read_csv. A transformação ocorreu na função tratar_dados, que padronizou textos, explicitou a ausência de gênero e removeu duas cópias completas. A gravação foi realizada com to_csv, sem índice. A remoção das cópias reduziu a base de 50 para 48 registros e a soma dos valores conhecidos de R$ 34.178,11

para R$ 32.965,85

# AUTOAVALIAÇÃO

Antes de entregar, responda SIM/NÃO:

- [ ] Meu projeto roda do início ao fim?
- [ ] Eu sei o que cada linha da base representa?
- [ ] Registrei nulos, duplicatas e inconsistências?
- [ ] Justifiquei a limpeza?
- [ ] Tenho duas funções com parâmetro e retorno?
- [ ] Calculei contagem, média, mínimo e máximo?
- [ ] Fiz um filtro?
- [ ] Fiz dois agrupamentos?
- [ ] Exportei sem índice?
- [ ] Escrevi 3 a 6 conclusões com números?
- [ ] Tenho recomendação e limitação?
- [ ] README explica como executar?
- [ ] O repositório possui commits que mostram progresso?